- name: httpd.conf settings
  tags: always
  replace: >-
    dest=/etc/httpd/conf/httpd.conf
    regexp='{{ item.regexp }}'
    replace='{{ item.replace }}'
  with_items:
  - regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
  - regexp: 'DocumentRoot.+'
    replace: 'DocumentRoot "/home/vagrant/workspace"'
  - regexp: '<Directory "/var/www/html">'
    replace: '<Directory "/home/vagrant/workspace">'
