# yum package update
- name: yum update
  shell: yum update -y
  become: yes
# yum package install
- name: install epel-release
  yum: name=epel-release state=latest
- name: install git
  yum: name=git state=latest
- name: install gcc
  yum: name=gcc state=latest
- name: install wget
  yum: name=wget state=latest
- name: install unzip
  yum: name=unzip state=latest
- name: install python-devel
  yum: name=python-devel state=latest
- name: install python-setuptools
  yum: name=python-setuptools state=latest
- name: install python-pip
  yum: name=python-pip state=latest
- name: install libselinux-python
  yum: name=libselinux-python state=latest
- name: install ld-linux.so.2
  yum: name=ld-linux.so.2 state=latest
- name: install libffi-devel
  yum: name=libffi-devel state=latest
- name: install openssl-devel
  yum: name=openssl-devel state=latest
# ansible
- name: install ansible
  pip: name=ansible state=latest
# config
- name: change timezone
  copy: src=/usr/share/zoneinfo/Japan dest=/etc/localtime
  become: yes
