- name: yum update
  shell: yum update -y
  become: yes
- name: install epel-release
  yum: name=epel-release state=latest
- name: set docker repository
  copy: src=docker.repo dest=/etc/yum.repos.d/
- name: install python-devel
  yum: name=python-devel state=latest
- name: install python-pip
  yum: name=python-pip state=latest
- name: update pip
  shell: pip install --upgrade pip
- name: install docker
  yum: name=docker-engine state=latest
- name: install docker-py
  pip: name=docker-py state=latest
- name: install docker-compose
  pip: name=docker-compose state=latest
- name: restart docker
  service: name=docker state=restarted
