- name: install jenkins plugins
  get_url: url="https://updates.jenkins-ci.org/latest/{{ item }}.hpi" dest=/var/lib/jenkins/plugins/
  with_items:
    - scm-api
    - git-client
    - git
    - ansible
    - thinBackup
    - buildtriggerbadge
    - jobConfigHistory
    - timestamper
    - monitoring
    - saferestart
    - simple-theme-plugin
- name: restart jenkins
  service: name=jenkins state=restarted
