# yum repository
- name: set docker repository
  copy: src=docker.repo dest=/etc/yum.repos.d/
# install docker
- name: install docker
  yum: name=docker-engine state=latest
- name: install docker-py
  pip: name=docker-py state=latest
- name: restart docker
  service: name=docker state=restarted

- name: docker mysql
  docker:
    # docker_api_version: 1.12
    name: webstream-mysql
    image: webstream/mysql
    state: started
    privileged: yes
    command: /sbin/init

- name: docker apache-php
  docker:
    # docker_api_version: 1.12
    name: apache-php
    image: tutum/apache-php
    state: started
    ports:
      - 80:80
