- name: docker run (Ruby2.2 application)
  shell: docker run -itd --name ruby22 docker/ruby /sbin/init
  sudo: yes
- name: copy ansible files to container (Ruby2.2 application)
  shell: tar -cv * | sudo docker exec -i ruby22 tar x -C /root/ansible chdir=ansible
  sudo: yes
# - name: copy config files to container (Ruby2.2 application)
#   shell: tar -cv * | sudo docker exec -i ruby22 tar x -C /root/secret_keys chdir=/var/tmp/secret_keys
#   sudo: yes
- name: docker provision (Ruby2.2 application)
  shell: docker exec -t ruby22 ansible-playbook -i "localhost," /root/ansible/settings.yml
  sudo: yes
