- name: copy repository config
  copy: src=filebeat.repo dest=/etc/yum.repos.d/ mode=0644
- name: install filebeat
  yum: name=filebeat state=latest
- name: beat to start automatically during boot
  shell: chkconfig --add filebeat
