- name: install logstash plugins
  become: yes
  command: "{{ls_home}}/bin/logstash-plugin install {{ item }}"
  register: plugin_installed
  with_items:
    - logstash-input-file
    - logstash-filter-grok
    - logstash-filter-csv
    - logstash-filter-mutate